export interface ETFInfo {
  ticker: string;
  name: string;
  category: string;
}

export const US_ETFS: ETFInfo[] = [
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", category: "Large Cap Blend" },
  { ticker: "QQQ", name: "Invesco QQQ Trust", category: "Technology" },
  { ticker: "SLV", name: "iShares Silver Trust", category: "Precious Metals" },
  { ticker: "GLD", name: "SPDR Gold Shares", category: "Precious Metals" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF", category: "Small Cap Blend" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", category: "Large Cap Blend" },
  { ticker: "TQQQ", name: "ProShares UltraPro QQQ", category: "Leveraged Technology" },
  { ticker: "GDX", name: "VanEck Gold Miners ETF", category: "Precious Metals" },
  { ticker: "SOXL", name: "Direxion Daily Semiconductor Bull 3X Shares", category: "Leveraged Technology" },
  { ticker: "AGQ", name: "ProShares Ultra Silver", category: "Leveraged Precious Metals" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF", category: "Large Cap Blend" },
  { ticker: "LQD", name: "iShares iBoxx Investment Grade Corporate Bond ETF", category: "Corporate Bonds" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", category: "Government Bonds" },
  { ticker: "SGOV", name: "iShares 0-3 Month Treasury Bond ETF", category: "Government Bonds" },
  { ticker: "TSLL", name: "Direxion Daily TSLA Bull 2X Shares", category: "Leveraged Single Stock" },
  { ticker: "SQQQ", name: "ProShares UltraPro Short QQQ", category: "Leveraged Inverse" },
  { ticker: "IBIT", name: "iShares Bitcoin Trust", category: "Cryptocurrency" },
  { ticker: "GLDM", name: "SPDR Gold MiniShares Trust", category: "Precious Metals" },
  { ticker: "IAU", name: "iShares Gold Trust", category: "Precious Metals" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial Average ETF Trust", category: "Large Cap Blend" },
  { ticker: "EFA", name: "iShares MSCI EAFE ETF", category: "International Developed" },
  { ticker: "XLF", name: "Financial Select Sector SPDR Fund", category: "Financial" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF", category: "Total Market" },
  { ticker: "SMH", name: "VanEck Semiconductor ETF", category: "Technology" },
  { ticker: "HYG", name: "iShares iBoxx High Yield Corporate Bond ETF", category: "High Yield Bonds" },
  { ticker: "RSP", name: "Invesco S&P 500 Equal Weight ETF", category: "Large Cap Blend" },
  { ticker: "XLK", name: "Technology Select Sector SPDR Fund", category: "Technology" },
  { ticker: "XLE", name: "Energy Select Sector SPDR Fund", category: "Energy" },
  { ticker: "IEFA", name: "iShares Core MSCI EAFE IMI Index ETF", category: "International Developed" },
  { ticker: "QQQM", name: "Invesco NASDAQ 100 ETF", category: "Technology" },
  { ticker: "IWF", name: "iShares Russell 1000 Growth ETF", category: "Large Cap Growth" },
  { ticker: "SOXS", name: "Direxion Daily Semiconductor Bear 3X Shares", category: "Leveraged Inverse" },
  { ticker: "PPLT", name: "abrdn Physical Platinum Shares ETF", category: "Precious Metals" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR Fund", category: "Healthcare" },
  { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", category: "Emerging Markets" },
  { ticker: "NVDL", name: "GraniteShares 1.5x Long NVDA Daily ETF", category: "Leveraged Single Stock" },
  { ticker: "IWD", name: "iShares Russell 1000 Value ETF", category: "Large Cap Value" },
  { ticker: "SIVR", name: "abrdn Physical Silver Shares ETF", category: "Precious Metals" },
  { ticker: "VXUS", name: "Vanguard Total International Stock ETF", category: "International" },
  { ticker: "XBI", name: "SPDR S&P Biotech ETF", category: "Biotechnology" },
  { ticker: "GDXJ", name: "VanEck Junior Gold Miners ETF", category: "Precious Metals" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", category: "International Developed" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF", category: "Emerging Markets" },
  { ticker: "SOXX", name: "iShares Semiconductor ETF", category: "Technology" },
  { ticker: "BIL", name: "SPDR Bloomberg 1-3 Month T-Bill ETF", category: "Government Bonds" },
  { ticker: "VGT", name: "Vanguard Information Technology ETF", category: "Technology" },
  { ticker: "EWY", name: "iShares MSCI South Korea ETF", category: "Country Specific" },
  { ticker: "AGG", name: "iShares Core U.S. Aggregate Bond ETF", category: "Aggregate Bonds" },
  { ticker: "FXI", name: "iShares China Large-Cap ETF", category: "Country Specific" },
  { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund", category: "Consumer Discretionary" },
  { ticker: "XLI", name: "Industrial Select Sector SPDR Fund", category: "Industrial" },
  { ticker: "ETHA", name: "VanEck Ethereum Strategy ETF", category: "Cryptocurrency" },
  { ticker: "XLP", name: "Consumer Staples Select Sector SPDR Fund", category: "Consumer Staples" },
  { ticker: "KRE", name: "SPDR S&P Regional Banking ETF", category: "Financial" },
  { ticker: "VTV", name: "Vanguard Value ETF", category: "Large Cap Value" },
  { ticker: "VCIT", name: "Vanguard Intermediate-Term Corporate Bond ETF", category: "Corporate Bonds" },
  { ticker: "IEMG", name: "iShares Core MSCI Emerging Markets IMI Index ETF", category: "Emerging Markets" },
  { ticker: "TZA", name: "Direxion Daily Small Cap Bear 3X Shares", category: "Leveraged Inverse" },
  { ticker: "MUB", name: "iShares National Muni Bond ETF", category: "Municipal Bonds" },
  { ticker: "SPYM", name: "SPDR Portfolio S&P 500 Momentum ETF", category: "Factor" },
  { ticker: "SILJ", name: "ETFMG Prime Junior Silver ETF", category: "Precious Metals" },
  { ticker: "XLU", name: "Utilities Select Sector SPDR Fund", category: "Utilities" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF", category: "Aggregate Bonds" },
  { ticker: "UGL", name: "ProShares Ultra Gold", category: "Leveraged Precious Metals" },
  { ticker: "SIL", name: "abrdn Physical Silver Shares ETF", category: "Precious Metals" },
  { ticker: "BITO", name: "ProShares Bitcoin Strategy ETF", category: "Cryptocurrency" },
  { ticker: "VUG", name: "Vanguard Growth ETF", category: "Large Cap Growth" },
  { ticker: "QLD", name: "ProShares Ultra QQQ", category: "Leveraged Technology" },
  { ticker: "SSO", name: "ProShares Ultra S&P500", category: "Leveraged Large Cap" },
  { ticker: "SCHD", name: "Schwab US Dividend Equity ETF", category: "Dividend" },
  { ticker: "USD", name: "ProShares Ultra Semiconductors", category: "Leveraged Technology" }
];